### ISSUE TITLE
/reset isn't working in 1.0.2

### ISSUE THREAD

**Issue by RocketGod-git** [Zero6992/chatGPT-discord-bot#219]
**Everything works excellent in 1.0.2 exept this error when using /reset:**<br><br>

Python310\site-packages\discord\app_commands\commands.py", line 880, in _do_call<br>
    raise CommandInvokeError(self, e) from e<br>
discord.app_commands.errors.CommandInvokeError: Command 'reset' raised an exception: AttributeError: module 'src.responses' has no attribute 'chatbot'

**Comment by Zero6992** [comment]
WIP

**Comment by Zero6992** [comment]
done
